/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PointType,
    PointTypeFromJSON,
    PointTypeFromJSONTyped,
    PointTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface GeneralPoint
 */
export interface GeneralPoint {
    /**
     * 
     * @type {number}
     * @memberof GeneralPoint
     */
    generalPointId?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralPoint
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof GeneralPoint
     */
    longitude?: number;
    /**
     * 
     * @type {PointType}
     * @memberof GeneralPoint
     */
    pointType: PointType;
}

export function GeneralPointFromJSON(json: any): GeneralPoint {
    return GeneralPointFromJSONTyped(json, false);
}

export function GeneralPointFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralPoint {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'generalPointId': !exists(json, 'generalPointId') ? undefined : json['generalPointId'],
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'pointType': PointTypeFromJSON(json['pointType']),
    };
}

export function GeneralPointToJSON(value?: GeneralPoint | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'generalPointId': value.generalPointId,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'pointType': PointTypeToJSON(value.pointType),
    };
}

