/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Point,
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
} from './';

/**
 * 
 * @export
 * @interface PointEncapsulation
 */
export interface PointEncapsulation {
    /**
     * 
     * @type {Point}
     * @memberof PointEncapsulation
     */
    point?: Point;
}

export function PointEncapsulationFromJSON(json: any): PointEncapsulation {
    return PointEncapsulationFromJSONTyped(json, false);
}

export function PointEncapsulationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointEncapsulation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'point': !exists(json, 'point') ? undefined : PointFromJSON(json['point']),
    };
}

export function PointEncapsulationToJSON(value?: PointEncapsulation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'point': PointToJSON(value.point),
    };
}

