/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApartmentRequest
 */
export interface ApartmentRequest {
    /**
     * 
     * @type {number}
     * @memberof ApartmentRequest
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentRequest
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentRequest
     */
    floor?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentRequest
     */
    levels?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentRequest
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentRequest
     */
    squareMeters?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentRequest
     */
    buildingFees?: number;
    /**
     * 
     * @type {string}
     * @memberof ApartmentRequest
     */
    description?: string;
}

export function ApartmentRequestFromJSON(json: any): ApartmentRequest {
    return ApartmentRequestFromJSONTyped(json, false);
}

export function ApartmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartmentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'levels': !exists(json, 'levels') ? undefined : json['levels'],
        'year': !exists(json, 'year') ? undefined : json['year'],
        'squareMeters': !exists(json, 'squareMeters') ? undefined : json['squareMeters'],
        'buildingFees': !exists(json, 'buildingFees') ? undefined : json['buildingFees'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ApartmentRequestToJSON(value?: ApartmentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'floor': value.floor,
        'levels': value.levels,
        'year': value.year,
        'squareMeters': value.squareMeters,
        'buildingFees': value.buildingFees,
        'description': value.description,
    };
}

