/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApartmentProjection
 */
export interface ApartmentProjection {
    /**
     * 
     * @type {number}
     * @memberof ApartmentProjection
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentProjection
     */
    floor?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentProjection
     */
    levels?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentProjection
     */
    squareMeters?: number;
    /**
     * 
     * @type {number}
     * @memberof ApartmentProjection
     */
    buildingFees?: number;
    /**
     * 
     * @type {string}
     * @memberof ApartmentProjection
     */
    description?: string;
}

export function ApartmentProjectionFromJSON(json: any): ApartmentProjection {
    return ApartmentProjectionFromJSONTyped(json, false);
}

export function ApartmentProjectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartmentProjection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'year': !exists(json, 'year') ? undefined : json['year'],
        'floor': !exists(json, 'floor') ? undefined : json['floor'],
        'levels': !exists(json, 'levels') ? undefined : json['levels'],
        'squareMeters': !exists(json, 'squareMeters') ? undefined : json['squareMeters'],
        'buildingFees': !exists(json, 'buildingFees') ? undefined : json['buildingFees'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function ApartmentProjectionToJSON(value?: ApartmentProjection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year': value.year,
        'floor': value.floor,
        'levels': value.levels,
        'squareMeters': value.squareMeters,
        'buildingFees': value.buildingFees,
        'description': value.description,
    };
}

