/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneralPointProjection
 */
export interface GeneralPointProjection {
    /**
     * 
     * @type {number}
     * @memberof GeneralPointProjection
     */
    generalPointId?: number;
    /**
     * 
     * @type {string}
     * @memberof GeneralPointProjection
     */
    pointType?: string;
}

export function GeneralPointProjectionFromJSON(json: any): GeneralPointProjection {
    return GeneralPointProjectionFromJSONTyped(json, false);
}

export function GeneralPointProjectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralPointProjection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'generalPointId': !exists(json, 'generalPointId') ? undefined : json['generalPointId'],
        'pointType': !exists(json, 'pointType') ? undefined : json['pointType'],
    };
}

export function GeneralPointProjectionToJSON(value?: GeneralPointProjection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'generalPointId': value.generalPointId,
        'pointType': value.pointType,
    };
}

